spring:
  application:
    name: eureka-client
  cloud:
    #获取配置中心的配置文件
    config:
      #指明远程仓库的分支
      label: master
      #dev开发环境配置文件
      #test测试环境
      #pro正式环境
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
#      uri: http://localhost:8888 #指明配置服务中心的网址
server:
  port: 2001
  servlet:
    context-path: /client
#注册
eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    hostname: localhost
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      # 开启健康检查（依赖spring-boot-starter-actuator）
    healthcheck:
      enabled: true
#swagger2
swagger:
  enabled: true
  title: com.dctest.www.eurekacline
  base-package: com.dctest.www.eurekacline
  version: 1.0.0.SNAPSHOT
  description: eureka-clinet
  contact:
    name: springCloud
    email: 123456@qq.com



