server:
  port: 8762

eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: eureka-client
          uri: lb://EUREKA-CLIENT
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

#
management:
  endpoints:
    web:
      exposure:
        include: '*'
#      security:
#        enabled: false


logging:
  level:
    com.example.gateway: debug

