server:
  port: 8764
spring:
  application:
    name: fegin

eureka:
  instance:
    hostname: localhost1
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# \u5F00\u542F\u65AD\u8DEF\u5668
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
